name: NoMorePhantoms
version: ${project.version}
main: com.cdejong.nomorephantoms.NoMorePhantoms
api-version: 1.15
permissions:
  nomorephantoms.nospawns:
    description: Phantoms spawns near players having this permission set are cancelled.
    default: op
